Escape button quit popups
dreamirl/de-plugin-popup pull request #2
Opened 2022-01-17 18:10 UTC by Sealed001

2022-01-17 18:13 UTC, Zeksa requested changes

2022-01-17 18:13 UTC, Zeksa commented on index.js
> +        this.removeAll();
non il faut trigger l'event 'pointerup' du bouton cancel/ok

2022-01-17 18:13 UTC, Zeksa commented on index.js
> +      if (event.key === "Escape") {
ça ne prend pas en compte le bouton b du gamepad

2022-01-18 10:57 UTC, Zeksa commented
https://trello.com/c/f3y8z0da/1067-esc-b-pour-quitter-les-popups

2022-01-18 16:13 UTC, Zeksa requested changes

2022-01-18 16:13 UTC, Zeksa commented on index.js
> +        if (closeCallback !== undefined) closeCallback(event);
closeCallback = undefined après l'avoir exécuté

2022-01-20 17:38 UTC, Inateno commented on index.js
>              var target = e.target;
Ici on aura un soucis du coup avec les popups custom car le "e" n'est pas défini via l'event gamepad.
Et même si on passait le e de l'event, ca ne serait pas bon car on aurai pas la "target" (l'élement cliqué).

Je pense qu'il faut donc prévoir ce cas de figure et donc passer un "e" avec le target name dedans (passé au moment du binding ?) ou alors que le e soit l'event "DE.Inputs" afin de connaitre la nom de l'input et pouvoir matcher le target comme ça

2022-01-21 16:56 UTC, merged